name: update-almas60

on:
  workflow_dispatch:
  schedule:
    - cron: " */10 * * * *"   # اجرای almas60.py هر 3 ساعت

permissions:
  contents: write

jobs:
  update-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests || echo "skip install"
      - run: timeout 600s python almas60.py || echo "❌ almas60.py failed or skipped"
      - run: |
          if [[ -s final60.txt || -s normal60.txt ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add final60.txt normal60.txt
            git commit -m "auto update from almas60.py [skip ci]" || echo "No changes"
            git push || echo "skip push"
          else
            echo "⚠️ final60.txt یا normal60.txt خالی یا موجود نیست، commit نشد"
          fi
